meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: cf_backup_z1
    template: cf_backup
    instances: 0
    persistent_disk: 102400
    resource_pool: small_z1
    networks: (( merge ))
  
networks: (( merge ))

properties: 
  ccdb_ng: (( merge ))
  uaadb: (( merge ))
  cf_backup: (( merge ))
