meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: cf_backup_leader_z1
    template: cf-backup
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
  - name: cf_backup_z1
    template: cf-backup
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    update:
      canaries: 10
    properties:
      cf_backup:
        master: (( merge ))

networks: (( merge ))

properties: {}
